repository_type: pipeline

nf_core_version: 3.5.1

lint: {}

template:
  org: nf-core
  name: nanocirc
  description: circRNA detection and analysis pipeline for long-read circRNA analysis
  author: Rusakovich Anastasia
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
